### PR TITLE
[JAX] Integrate BF16 Grouped GEMM with on-device group sizes

### LINKED ISSUE #2659: [Core] TE common nvte_grouped_gemm treats output layout as column-wise instead of rowwise
**Describe the bug**

Output layout is assumed to be column-wise instead of row-wise in the nvte_grouped_gemm API

**Steps/Code to reproduce bug**

Please list *minimal* steps or code snippet for us to be able to reproduce the bug.

A  helpful guide on on how to craft a minimal bug report  http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports. 

**Expected behavior**

**Environment overview (please complete the following information)**

 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider - AWS, Azure, GCP, Collab)]
 - Method of Transformer Engine install: [pip install or from source]. Please specify exact commands you used to install.
 - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- OS version
- PyTorch version
- Python version
- Transformer Engine version
- CUDA version
- CUDNN version

**Device details**
- GPU model

**Additional context**

### PR DESCRIPTION
**Pull request by jberchtold-nvidia**
# Description

Integrate new BF16 grouped GEMM from TE common/cuBLASLt that supports on-device group sizes without a D2H memcpy and stream sync. This grouped GEMM is faster and CUDA-graph safe.

Also fixes #2659

## Type of change

- [ ] Documentation change (change only to the documentation, either a fix or a new content)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Infra/Build change
- [ ] Code refactoring

## Changes

- Added a new cuda-graph-safe grouped GEMM to TE/JAX that is automatically used as the backend when the input data is bf16 (no scaling recipe) and not bias is required.
- Exposed a new `make_ragged_dot_cls` for easy integration into existing models. This will be most useful when quantization is supported and storing recipe state is required

# Checklist:

- [x] I have read and followed the [contributing guidelines](https://github.com/NVIDIA/TransformerEngine/blob/main/CONTRIBUTING.rst)
- [x] The functionality is complete
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: transformer_engine/jax/csrc/extensions/gemm.cpp [hunk 1]
```diff
@@ -409,6 +409,397 @@ XLA_FFI_DEFINE_HANDLER_SYMBOL(GroupedGemmD2HGroupSizesHandler, GroupedGemmD2HGro
                                   .Ret<Buffer_Type>()      // dummy_output
                                   .Attr<int64_t>("num_gemms"));
 
+class JAXX_GroupedTensorWrapper {
```
Comment (jberchtold-nvidia) [inline transformer_engine/jax/csrc/extensions/gemm.cpp:412]: There is a PyTorch refactor PR that also adds a similar GroupedTensorWrapper struct to TE/common. I will move to that in the future once it is merged, but I don't want to block this PR on that currently and the logic is pretty straightforward and should be a small change to switch.

File: transformer_engine/common/gemm/cublaslt_grouped_gemm.cu [hunk 2]
```diff
@@ -535,6 +553,10 @@ inline size_t grouped_gemm_setup_workspace_size(size_t num_tensors) {
 
 }  // namespace
 
+size_t nvte_grouped_gemm_setup_workspace_size(size_t num_tensors) {
+  return grouped_gemm_setup_workspace_size(num_tensors);
```
Comment (phu0ngng) [inline transformer_engine/common/gemm/cublaslt_grouped_gemm.cu]: Register `nvte_` API with `NVTE_API_CALL`.

File: transformer_engine/jax/csrc/extensions/gemm.cpp [hunk 3]
```diff
@@ -409,6 +409,383 @@ XLA_FFI_DEFINE_HANDLER_SYMBOL(GroupedGemmD2HGroupSizesHandler, GroupedGemmD2HGro
...
+                                  .Ret<Buffer_Type>()      // int64_workspace
+                                  .Attr<int64_t>("M")
+                                  .Attr<int64_t>("N")
+                                  .Attr<int64_t>("K")
+                                  .Attr<bool>("lhs_is_trans")
+                                  .Attr<bool>("rhs_is_trans")
+                                  .Attr<JAXX_Scaling_Mode>("scaling_mode")
+                                  .Attr<bool>("has_bias")
+                                  .Attr<bool>("is_grouped_dense_wgrad")
+                                  .Attr<bool>("use_async_d2h_group_sizes"),
```
Comment (phu0ngng) [inline transformer_engine/jax/csrc/extensions/gemm.cpp]: Remove these three attributes as they are not needed.

File: transformer_engine/jax/csrc/extensions/gemm.cpp [hunk 4]
```diff
@@ -409,6 +409,383 @@ XLA_FFI_DEFINE_HANDLER_SYMBOL(GroupedGemmD2HGroupSizesHandler, GroupedGemmD2HGro
...
+  nvte_grouped_gemm(rhs_tensor, rhs_is_trans, lhs_tensor, lhs_is_trans, nullptr, out_tensor,
+                    alpha_tensor.data(), beta_tensor.data(), workspace_setup.data(),
+                    workspace_cublas.data(),
+                    nullptr,  // config (use defaults)
+                    stream);
+
+  return ffi_with_cuda_error_check();
+}
+
+XLA_FFI_DEFINE_HANDLER_SYMBOL(GroupedGemmCudaGraphableHandler, GroupedGemmCudaGraphableFFI,
```
Comment (phu0ngng) [inline transformer_engine/jax/csrc/extensions/gemm.cpp]: Should we simply call it v2 for now and eventually rename it back to GroupedGEMM? 

Besides, if it is possible, could we mark it as an experimental API and subject to changes?

File: transformer_engine/jax/cpp_extensions/gemm.py [hunk 5]
```diff
@@ -1910,6 +1983,28 @@ def grouped_gemm_copy_group_sizes(
...
+    # feature-compatible with the main branch.
+    # Bias can be supported in a kernel or in pure-JAX in the future.
+
+    try:
+        get_grouped_gemm_setup_workspace_size(1)
+    except RuntimeError as e:
+        if "cublas" in str(e).lower():
+            # If the workspace size function is not available, it means the cuda-graphable implementation is not available.
+            return False
+        raise e
```
[the remark this answers is not in the document]
Comment (phu0ngng) [reply transformer_engine/jax/cpp_extensions/gemm.py]: I'm not sure about this helper. 

Why don't we simply check for NO_SCALING, then go with the v2?

Also, we should be able to check it inside primitive methods instead of passing it as an argument so that when we eventually remove the multi-stream approach, we don't need to change the primitive inputs.

File: transformer_engine/jax/flax/module.py [hunk 6]
```diff
@@ -1438,3 +1441,26 @@ def te_dot_general(generate_quantizer_set, x, kernel, dims, **kwargs):
...
+            kernel,
+            group_sizes=group_sizes,
+            contracting_dims=((1,), (1,)),
+            quantizer_set=quantizer_set,
+        )
+        return out
+
+    return wrap_function_in_te_state_module(
+        te_grouped_dot_general, quantization_recipe, "ragged_dot"
+    )()
```
[the remark this answers is not in the document]
Comment (phu0ngng) [reply transformer_engine/jax/flax/module.py:1466]: Should we call it grouped_dense here to be consistent?

File: transformer_engine/common/include/transformer_engine/gemm.h [hunk 7]
```diff
@@ -329,6 +329,31 @@ void nvte_multi_tensor_gemm(const NVTETensor *A, const NVTETensor *B, NVTETensor
...
+ * The setup workspace stores pointer arrays and per-matrix dimension arrays used
+ * by the grouped GEMM kernel. Its size depends only on the number of tensors (GEMMs)
+ * in the group and is independent of matrix dimensions.
+ *
+ * Pass the result as the size of the workspace_setup tensor in nvte_grouped_gemm.
+ *
+ *  \param[in] num_tensors  Number of tensors (GEMMs) in the group.
+ *  \return Required size in bytes for workspace_setup.
+ */
+size_t nvte_grouped_gemm_setup_workspace_size(size_t num_tensors);
```
Comment (phu0ngng) [inline transformer_engine/common/include/transformer_engine/gemm.h]: Nit: could we add `get` i.e., `nvte_get_grouped_gemm_setup_workspace_size`? :D

File: transformer_engine/jax/cpp_extensions/gemm.py (hunk 5 above)
[the remark this answers is not in the document]
Comment (jberchtold-nvidia) [reply transformer_engine/jax/cpp_extensions/gemm.py]: > Why don't we simply check for NO_SCALING, then go with the v2?

In addition to NO_SCALING, we need to check the cuBLAS version. In fact, more than that, we need to check the cuBLAS version TE was built with, which may not be the same depending on how the user installed TE. Otherwise, we will dispatch to v2 but it will fail during lowering because the C++ functions raise an error in TE core based on the cuBLAS version it was compiled with. In this case, instead of erroring, I'd rather keep the old behavior and fall back to the slower implementation.

> Also, we should be able to check it inside primitive methods instead of passing it as an argument so that when we eventually remove the multi-stream approach, we don't need to change the primitive inputs.

I was planning to do this originally but ran into two issues:
1. I needed to check which backend we're using (original or V2) in multiple places in the primitive. The abstract requires it and the lowering requires it. In the lowering, we don't have easy access to dtype as it's not a jnp.dtype it's some mlir dtype that isn't as easy to convert.
2. The MLIR `ctx` bakes in information about the inputs. You can't simply slice `args` in lowering and pick and choose which primitive to dispatch to. If you do, it'll give an MLIR error that the `ctx` and `args` don't match. As a result, I'd have to update the original FFI to accept `alpha` and `beta` which would break FFI compatibility. Which is why I've gone with the solution of passing additional_arg_0 and additional_arg_1 which needs to happen outside the primitive. This isn't ideal, but was required to get around this fixed arg limitation. Additionally, the static arg indices are fixed at primitive registration and currently the original FFI and the V2 FFI take a different number of args, so for the original FFI I have to use an unused addtional_arg_1 in the outer impl.

As a result of both of these, it's simpler to just check once outside the primitive whether we should use the original or V2, then pass that as a bool flag. Given these restrictions of 1. and 2., I'm not sure this consolidated primitive is a cleaner solution than the split primitives (unless I can break FFI compatibility to unify the FFIs to make the original FFI take alpha and beta).

File: transformer_engine/common/include/transformer_engine/gemm.h (hunk 7 above)
Comment (jberchtold-nvidia) [reply transformer_engine/common/include/transformer_engine/gemm.h]: Updated

File: transformer_engine/jax/csrc/extensions/gemm.cpp (hunk 4 above)
Comment (jberchtold-nvidia) [reply transformer_engine/jax/csrc/extensions/gemm.cpp]: Sounds good, renamed to V2

File: transformer_engine/jax/csrc/extensions/gemm.cpp (hunk 3 above)
Comment (jberchtold-nvidia) [reply transformer_engine/jax/csrc/extensions/gemm.cpp]: Removed has_bias and use_async_d2h_group_sizes. The `is_grouped_dense_wgrad` is still required currently but I agree in future we should refactor this logic

File: transformer_engine/common/gemm/cublaslt_grouped_gemm.cu (hunk 2 above)
Comment (jberchtold-nvidia) [reply transformer_engine/common/gemm/cublaslt_grouped_gemm.cu]: Done

File: transformer_engine/jax/flax/module.py (hunk 6 above)
[the remark this answers is not in the document]
Comment (jberchtold-nvidia) [reply transformer_engine/jax/flax/module.py:1466]: Updated to rename to grouped_dense
